spring:
  datasource:
    username: snakegame
    password: 123456
    url: jdbc:derby:blogDb;create=true
    driver-class-name: org.apache.derby.jdbc.EmbeddedDriver
    schema: classpath:schema.sql
    data: classpath:data.sql
    initialization-mode: always
    continue-on-error: true
