# Tomcat
# Here is the local ip address of the
server:
  address: 192.168.1.156
  port: 8080

#spring
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite::resource:schema.db
    username:
    password:


